kind: pipeline
name: builder image

steps:
- name: build
  image: plugins/docker
  settings:
    repo: local/arch-repo-build

---
kind: pipeline
name: build packages and deploy

steps:
- name: build yay
  image: local/arch-repo-build
  commands:
  - git clone https://aur.archlinux.org/yay.git
  - export PKGBUILD=$PWD
  - /build.sh $PWD/yay
  - ls -la

depends_on:
- builder image