kind: pipeline
name: builder image

steps:
- name: build
  image: plugins/docker
  settings:
    repo: registry.d-jensen.de/danto7/arch-repo-build
    registry: registry.d-jensen.de
    username:
      from_secret: docker-user
    password:
      from_secret: docker-password
---
kind: pipeline
name: build packages and deploy

steps:
- name: build yay
  image: registry.d-jensen.de/danto7/arch-repo-build
  commands:
  - git clone https://aur.archlinux.org/yay.git
  - export PKGBUILD=$PWD
  - /build.sh $PWD/yay
  - ls -lah

depends_on:
- builder image